# The URL the site will be built for
base_url = "https://codetriangle.me"

title = "CodeTriangle's Curiosities"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "zola-bearblog"

feed_filenames = [ "atom.xml", "rss.xml" ]

[[taxonomies]]
name = "tags"
feed = true

[markdown.highlighting]
style = "inline"
theme = "gruvbox-dark-medium"

[extra]
# Put all your custom variables here

date_format = "%-d %B %Y"

[[extra.main_menu]]
name = "Tech Blog"
url = "@/blog/_index.md"

[[extra.main_menu]]
name = "Projects"
url = "@/projects/_index.md"

[[extra.main_menu]]
name = "Game Reviews"
url = "@/reviews/_index.md"
